[package]
name = "rustiv"
version = "0.1.0"
edition = "2021"

[dependencies.reqwest]
version = "0.11"
features = ["blocking", "json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies]
serde_json = "1.0"